### ISSUE TITLE
feat: Update context feature

### ISSUE THREAD

**Issue by DCampagnola** [rizentium/unleash-flutter-proxy-sdk#4]
**Description**

I'm looking for a way to update context once Unleash has been initialized, I've tried to call `initializeApp` as a workaround to update context, but it created a new timer duplicating the requests.

**Requirements**

- [ ] add `updateContext` in `Unleash` class or `UnleashContext`

**Comment by rizentium** [comment]
I still working on it. Thank you for your feedback
